name: Native Rialto Build

on:
  pull_request:
    branches: [ "master", "rdkcentral:master" ]
  push:
    branches: [ "master", "rdkcentral:master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        path: rialto-ocdm

      - name: Check out rialto
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/rialto
          path: ./rialto

      - name: Check out rialto-gstreamer
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/rialto-gstreamer
          path: ./rialto-gstreamer

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install cmake
          sudo apt-get install libunwind-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer1.0-dev

      - name: Install protobuf
        run: |
          sudo apt-get install protobuf-compiler

      - name: Build Rialto
        run: |
          BASE_DIR=$(pwd)
          NATIVE_DIR=$BASE_DIR/native
          cd rialto
          cmake . -B build  -DCMAKE_INSTALL_PREFIX=$NATIVE_DIR -DNATIVE_BUILD=ON -DRIALTO_BUILD_TYPE="Debug" &> $BASE_DIR/output_file.txt
          if [ $? -ne 0 ]
          then
            exit 1
          fi
          make -C build &>> $BASE_DIR/output_file.txt
          if [ $? -ne 0 ]
          then
            exit 1
          fi
          cd ../rialto-gstreamer
          cmake . -B build -DCMAKE_INCLUDE_PATH="${NATIVE_DIR}/include" -DCMAKE_LIBRARY_PATH="${NATIVE_DIR}/lib" -DNATIVE_BUILD=ON -DRIALTO_BUILD_TYPE="Debug" &>> $BASE_DIR/output_file.txt
          if [ $? -ne 0 ]
          then
            exit 1
          fi
          make $makeOpts -C build  &>> $BASE_DIR/output_file.txt
          if [ $? -ne 0 ]
          then
            exit 1
          fi
          cd ../rialto-ocdm
          cmake . -B build -DCMAKE_INCLUDE_PATH="${NATIVE_DIR}/include"  -DCMAKE_LIBRARY_PATH="${NATIVE_DIR}/lib" -DNATIVE_BUILD=ON -DRIALTO_BUILD_TYPE="Debug" &>> $BASE_DIR/output_file.txt
          if [ $? -ne 0 ]
          then
            exit 1
          fi
          make $makeOpts -C build &>> $BASE_DIR/output_file.txt
          if [ $? -ne 0 ]
          then
            exit 1
          fi

      - name: Report Build Status Success
        if: success()
        run: |
          echo "Build Succeeded!"
          exit 0

      - name: Upload Logs on Failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Output Logs
          path: |
            output_file.txt